server:
  port: 80

eureka:
  client:
    register-with-eureka: false   #需要访问eureka，获取注册信息，但是不会将本实例注册进eureka
    service-url:      #访问eureka的备选路径
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
