server:
  port: 8003

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.lh708.springcloud.entities    # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mappers/**/*.xml                       # mapper映射文件

spring:
   application:
    name: microservicecloud-dept
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource              # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver                # mysql驱动包
    url: jdbc:mysql://localhost:3306/cloudDB3                      # 数据库名称
    username: root
    password:
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: microservice-deparment8003           #配置在Eureka列表中显示的别名
    prefer-ip-address: true                          #配置在当鼠标放置在Eureka列表中时，是否在左下角状态栏显示IP地址

info:
  app.name: lh708-microservicecloud
  company.name: lh708
  build.artifactId: $project.artifactId$
  build.version: $project.version$